### ISSUE TITLE
When I use GPU to train the model, I will have problem 'CUDA out of memory...'

### ISSUE THREAD

**Issue by RobinLu1209** [FelixOpolka/STGCN-PyTorch#7]
Is there someone who also has this problem?

**Comment by Cestbo** [comment]
me too

**Comment by RobinLu1209** [comment]
> me too

I have solved this problem. I remember that there are some code written like to be [to(device='cpu')]
You can change these code to be 'cuda', and have a try again. Maybe you will solve this problem.

**Comment by Cestbo** [comment]
> Is there someone who also has this problem?


> > me too
> 
> I have solved this problem. I remember that there are some code written like to be [to(device='cpu')]
> You can change these code to be 'cuda', and have a try again. Maybe you will solve this problem.

thank you ,i will try. i always think my gpu is weak

**Comment by Noahprog** [comment]
Nah, the problem is in validation method! In training '_batch_size_' is used to prevent memory overload, but when validating it passes in the whole validation set. This means memory gets blown up.

**Comment by vsfh** [comment]
> Nah, the problem is in validation method! In training '_batch_size_' is used to prevent memory overload, but when validating it passes in the whole validation set. This means memory gets blown up.

do you know how to fix it, thx

**Comment by Noahprog** [comment]
Yes, but I don’t have time to do it for you. The solution is to rewrite the validation to also work with batches.

The training is already done this way, so that is a nice example for this.

**Comment by LiaoLW** [comment]
> > Nah, the problem is in validation method! In training '_batch_size_' is used to prevent memory overload, but when validating it passes in the whole validation set. This means memory gets blown up.
> 
> do you know how to fix it, thx

Change the split line into about 0.9/0.95, then my problem solved
![image](https://user-images.githubusercontent.com/49851668/92317556-90693100-f034-11ea-8b84-18f9a3bbd75d.png)

**Comment by Coolgiserz** [comment]
I change the dataset split (0.8/0.1/0.1) and solve this problem.
